version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
    groups:
      bb84-dependencies:
        patterns:
          - "BB84*"
      mstest-dependencies:
        patterns:
          - "MSTest*"
      microsoft-dependencies:
        patterns:
          - "Microsoft*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
