<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="MSTest"/>
		<PackageReference Include="coverlet.collector">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\SSRS.Brand.Editor.Domain\SSRS.Brand.Editor.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <None Update="TestResources\colors.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="TestResources\metadata.xml">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>
</Project>
