<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\..\src\SSRS.Brand.Editor.Domain\SSRS.Brand.Editor.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Update="TestFiles\colors.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="TestFiles\metadata.xml">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>

</Project>
