<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>SSRS.Brand.Editor.ico</ApplicationIcon>
	</PropertyGroup>

	<ItemGroup>
		<Content Include="SSRS.Brand.Editor.ico" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SSRS.Brand.Editor.Infrastructure\SSRS.Brand.Editor.Infrastructure.csproj" />
		<ProjectReference Include="..\SSRS.Brand.Editor.Presentation\SSRS.Brand.Editor.Presentation.csproj" />
	</ItemGroup>

</Project>
