<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<ApplicationIcon>ApplicationIcon.ico</ApplicationIcon>
		<TargetFramework>net8.0-windows</TargetFramework>
		<OutputType>WinExe</OutputType>
		<UseWPF>true</UseWPF>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\SSRS.Brand.Editor.Infrastructure\SSRS.Brand.Editor.Infrastructure.csproj" />
		<ProjectReference Include="..\SSRS.Brand.Editor.Presentation\SSRS.Brand.Editor.Presentation.csproj" />
	</ItemGroup>
</Project>
