<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType Condition="$(Configuration.Equals('Release'))">WinExe</OutputType>
		<OutputType Condition="$(Configuration.Equals('Debug'))">Exe</OutputType>
		<UseWPF>True</UseWPF>
		<StartupObject>SSRS.Brand.Editor.App</StartupObject>
		<ApplicationIcon>ApplicationIcon.ico</ApplicationIcon>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="ApplicationIcon.ico" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SSRS.Brand.Editor.Infrastructure\SSRS.Brand.Editor.Infrastructure.csproj" />
		<ProjectReference Include="..\SSRS.Brand.Editor.Presentation\SSRS.Brand.Editor.Presentation.csproj" />
	</ItemGroup>
	<ItemGroup>
		<None Update="appsettings.Development.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="appsettings.Production.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	</ItemGroup>
</Project>