<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="MSTest" />
		<PackageReference Include="coverlet.collector">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\src\SSRS.Brand.Editor.Application\SSRS.Brand.Editor.Application.csproj" />
	</ItemGroup>
</Project>
