<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup />
  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="MSTest" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SSRS.Brand.Editor.Domain\SSRS.Brand.Editor.Domain.csproj" />
  </ItemGroup>
</Project>