<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<ProjectReference Include="..\SSRS.Brand.Editor.Domain\SSRS.Brand.Editor.Domain.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="Interfaces\Infrastructure\Persistence\" />
		<Folder Include="Interfaces\Presentation\Services\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="BB84.Notifications" Version="3.2.520" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Logging" Version="8.0.0" />
	</ItemGroup>

</Project>