<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\SSRS.Brand.Editor.Domain\SSRS.Brand.Editor.Domain.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Folder Include="Interfaces\Infrastructure\Persistence\" />
		<Folder Include="Interfaces\Presentation\Services\" />
	</ItemGroup>
</Project>