<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
	  <PackageReference Include="DotNetProjects.Extended.Wpf.Toolkit" Version="5.0.115" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\SSRS.Brand.Editor.Application\SSRS.Brand.Editor.Application.csproj" />
	</ItemGroup>

</Project>