<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.Logging.Console" />
	  <PackageReference Include="Microsoft.Extensions.Logging.EventLog" />
	</ItemGroup>	
	<ItemGroup>
		<ProjectReference Include="..\SSRS.Brand.Editor.Application\SSRS.Brand.Editor.Application.csproj" />
	</ItemGroup>
</Project>